server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transitdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user
      password: password

logging:
  level:
    root: INFO
    com.capetown.transit: DEBUG

external:
  api:
    base-url: https://api.capetown.gov.za/opendata
    key: ${EXTERNAL_API_KEY:your_api_key_here}
