server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:transitdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user
      password: password

logging:
  level:
    root: INFO
    com.capetown.transit: DEBUG

external:
  api:
    base-url: https://api.capetown.gov.za/opendata
    key: ${EXTERNAL_API_KEY:your_api_key_here}
