FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /workspace

COPY pom.xml ./
COPY src ./src

RUN mvn -q -DskipTests -Dmaven.test.skip=true package spring-boot:repackage

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /workspace/target/transit-1.0.0.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
